"""Deterministic HSK level check for Mandarin (_ZH) review edits — the vocabulary half of
Gate 1 (docs/auto-review-proposal.md).

Origin (2026-07-13): Gate 2 (Claude Sonnet) was asked to judge "is this word above the
trip's HSK level?" and it was wrong about as often as it was right on Ted's six scripts —
it flagged 离开 (HSK2) and 保持 (HSK3) as above-level, invented band numbers, and *cleared*
旧 as "HSK2" when it is HSK3 (out of band for an HSK12 trip). Meanwhile the content
pipeline already ships a real checker. This module brings that check into the review app so
"above level" is a lookup, not an opinion. Gate 2's LEVEL item was removed in the same pass.

MIRRORS ``Scripts/Research and Writing/HSK Mandarin/stages/level_check.py`` (Checker.
eval_word / check_text) and must keep matching it — same POS filter, same compound-rescue
rule, same proper-noun handling. It does NOT import that module, because level_check reads
hsk_vocab.xlsx and ``*.xlsx`` is gitignored in dynamic-content: the file exists only on the
machine that built it, so an import would work here and silently fail on the live laptop.
Instead we read a committed JSON snapshot (``app/data/hsk_vocab.json``, regenerated by
``scripts/export_hsk_vocab.py``) and segment with jieba, which the live venv has.

NEVER BLOCKS — out-of-band vocabulary is a legitimate authoring choice (the pipeline calls
these i+1 words and lets an author declare them). This surfaces it as a warning so the
choice is conscious. Degrades to silence if jieba or the snapshot is unavailable.
"""
from __future__ import annotations

import json
import re
import threading
from functools import lru_cache
from pathlib import Path

_SNAPSHOT = Path(__file__).resolve().parent / "data" / "hsk_vocab.json"

# jieba POS first-letters counted as VOCABULARY content words (level_check.CONTENT_PREFIX).
# Everything else (pronouns, prepositions, conjunctions, particles, measure words,
# numerals, punctuation) is basic grammar and automatically in band.
_CONTENT_PREFIX = ("n", "v", "a", "d", "t", "s", "z", "l", "i", "b")
_HAN = re.compile(r"[一-鿿]")

# KNOWN DIVERGENCE from level_check.py: that script calls jieba.add_word() for each
# multi-char proper noun so segmentation keeps e.g. 太阳饼 whole. We deliberately DON'T —
# add_word mutates the PROCESS-GLOBAL tokenizer that hsk_lib's pinyin regeneration also
# uses, and in this long-lived server it would pool every trip's nouns across trips. Cost:
# jieba may split a newly-added proper noun and a leftover single char can be flagged
# (WARN only, and only when the edit introduced it). Serialise construction anyway so two
# threads don't race jieba's lazy dictionary init.
_LOCK = threading.Lock()


def trip_band(trip_id: str) -> str | None:
    """'Taichung_HSK3_ZH' -> 'HSK3'. None if the trip has no HSK band (not a _ZH trip)."""
    m = re.search(r"_(HSK12|HSK3)_ZH$", trip_id or "")
    return m.group(1) if m else None


def trip_base(trip_id: str) -> str:
    """'Taichung_HSK3_ZH' -> 'Taichung_EN' (the key of hsk_config.TRIPS)."""
    return re.sub(r"_(HSK12|HSK3)_ZH$", "_EN", trip_id or "")


@lru_cache(maxsize=1)
def _snapshot() -> dict | None:
    try:
        return json.loads(_SNAPSHOT.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001 — missing/corrupt snapshot = degrade to silence
        return None


@lru_cache(maxsize=1)
def _pseg():
    """Lazy jieba import (heavy; absent in some envs). None if unavailable."""
    try:
        import jieba.posseg as pseg
        return pseg
    except Exception:  # noqa: BLE001
        return None


class Checker:
    """One band's view of the vocabulary. Cheap to build once the snapshot is loaded."""

    def __init__(self, snap: dict, band: str, trip_id: str):
        self.band = band
        self.surfaces: dict[str, str] = snap["surfaces"]
        self.in_band: set[str] = set(snap["bands"][band])
        self.proper: set[str] = set(snap.get("proper_base") or [])
        self.proper |= set((snap.get("proper_by_trip") or {}).get(trip_base(trip_id)) or [])
        # Characters appearing in ANY in-band word — the compound-rescue alphabet.
        self.inband_chars: set[str] = set()
        for surf, lvl in self.surfaces.items():
            if lvl in self.in_band:
                self.inband_chars.update(c for c in surf if _HAN.match(c))

    def _is_proper(self, w: str) -> bool:
        if w in self.proper:
            return True
        if len(w) >= 2:
            for p in self.proper:
                if len(p) >= 2 and (w in p or p in w):
                    return True
        return False

    def eval_word(self, w: str) -> tuple[str, str | None]:
        """('in'|'proper'|'compound'|'out', level_label_or_None) — level_check.eval_word."""
        if self._is_proper(w):
            return "proper", None
        lvl = self.surfaces.get(w)
        if lvl is not None:
            return ("in", lvl) if lvl in self.in_band else ("out", lvl)
        # A single hanzi not in the wordlist is in band iff it occurs in an in-band word.
        if len(w) == 1 and _HAN.match(w):
            return ("in", "char") if w in self.inband_chars else ("out", None)
        # Compound rescue: an unlisted multi-char word whose every hanzi is in-band is
        # treated as in band (this is what passes 老旧, 台风, 月台 — see docs).
        han = [c for c in w if _HAN.match(c)]
        if han and all(c in self.inband_chars for c in han):
            return "compound", None
        return "out", None

    def _proper_spans(self, text: str) -> set[int]:
        """Character indices covered by a multi-char proper noun occurring in `text`.

        level_check achieves this with ``jieba.add_word(name)``, which keeps 太阳饼 whole so
        jieba can't split it into 太阳 + 饼 and leak the leftover 饼 as out-of-band. We must
        NOT do that here: add_word mutates the process-global tokenizer that hsk_lib's pinyin
        regeneration also uses, inside a long-lived server, and would pool every trip's names.
        Masking the spans instead gets the same answer with no global state.
        """
        spans: set[int] = set()
        for name in self.proper:
            if len(name) < 2:
                continue
            start = text.find(name)
            while start != -1:
                spans.update(range(start, start + len(name)))
                start = text.find(name, start + 1)
        return spans

    def out_words(self, text: str) -> dict[str, str]:
        """Ordered {out-of-band content word -> known HSK level or 'not-in-list'}."""
        pseg = _pseg()
        text = text or ""
        spans = self._proper_spans(text)
        out: dict[str, str] = {}
        pos = 0
        for tok in pseg.cut(text):
            w, flag = tok.word, tok.flag
            start, pos = pos, pos + len(w)              # jieba's tokens re-concatenate to text
            if not _HAN.search(w):                      # punctuation / latin / digits
                continue
            if any(i in spans for i in range(start, pos)):
                continue                                # inside a proper noun — exempt
            if not flag.startswith(_CONTENT_PREFIX):    # function word = basic grammar
                continue
            status, lvl = self.eval_word(w)
            if status == "out":
                out.setdefault(w, lvl or "not-in-list")
        return out


def checker_for(trip_id: str) -> Checker | None:
    """The Checker for this trip's band, or None if the check can't run here."""
    band = trip_band(trip_id)
    snap = _snapshot()
    if band is None or snap is None or _pseg() is None:
        return None
    if band not in (snap.get("bands") or {}):
        return None
    with _LOCK:
        return Checker(snap, band, trip_id)


def introduced_out_of_band(orig: str, cur: str, chk: Checker) -> dict[str, str]:
    """Out-of-band content words the EDIT added: present in `cur`, absent from `orig`.

    A diff — not an absolute count — on purpose. The approved draft already contains
    out-of-band words that its author declared as deliberate i+1 vocabulary; nagging a
    reviewer about those would be noise they cannot act on. Only what this edit newly
    introduced is theirs to answer for.
    """
    before = chk.out_words(orig)
    return {w: lvl for w, lvl in chk.out_words(cur).items() if w not in before}


def band_label(band: str) -> str:
    return "HSK 1-2" if band == "HSK12" else "HSK 1-3"
